### ISSUE TITLE
[SafeComp] safe

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#101]
```yaml
category: Ops
component: SafeComp
impact: safe
severity: low
status: todo
suggestion: noop
```
