### ISSUE TITLE
[MoviesSpider vs Orchestrator] Overlapping responsibilities blur ownership; harder to unit-test

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#24]
**Component:** MoviesSpider vs Orchestrator
**Category:** Architecture
**Severity:** high

### Impact
Overlapping responsibilities blur ownership; harder to unit-test

### Suggestion
Let Orchestrator own classification/extraction; Spider handles I/O only

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: MoviesSpider vs Orchestrator
category: Architecture
severity: high
impact: Overlapping responsibilities blur ownership; harder to unit-test
suggestion: Let Orchestrator own classification/extraction; Spider handles I/O only
status: todo
```
