### ISSUE TITLE
[PageClassifier (rule-based)] Static thresholds break on layout shifts; brittle at scale

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#25]
**Component:** PageClassifier (rule-based)
**Category:** Architecture
**Severity:** medium

### Impact
Static thresholds break on layout shifts; brittle at scale

### Suggestion
Add rule-firing telemetry + prepare dataset for lightweight ML fallback

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: PageClassifier (rule-based)
category: Architecture
severity: medium
impact: Static thresholds break on layout shifts; brittle at scale
suggestion: Add rule-firing telemetry + prepare dataset for lightweight ML fallback
status: todo
```
