### ISSUE TITLE
[Site Profiles] Treating every site identically causes unnecessary fallbacks & noise

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#26]
**Component:** Site Profiles
**Category:** Architecture
**Severity:** medium

### Impact
Treating every site identically causes unnecessary fallbacks & noise

### Suggestion
YAML/JSON "site profile" layer (selectors, JS flag, field map, rate limit)

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Site Profiles
category: Architecture
severity: medium
impact: Treating every site identically causes unnecessary fallbacks & noise
suggestion: YAML/JSON "site profile" layer (selectors, JS flag, field map, rate limit)
status: todo
```
