### ISSUE TITLE
[Crawl Resume / Checkpointing] Long jobs lose progress on crash; duplicates on restart

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#27]
**Component:** Crawl Resume / Checkpointing
**Category:** Architecture
**Severity:** medium

### Impact
Long jobs lose progress on crash; duplicates on restart

### Suggestion
Persist crawl state (scrapy-checkpoint or Redis queue) for resume

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Crawl Resume / Checkpointing
category: Architecture
severity: medium
impact: Long jobs lose progress on crash; duplicates on restart
suggestion: Persist crawl state (scrapy-checkpoint or Redis queue) for resume
status: todo
```
