### ISSUE TITLE
[SeleniumManager coupling] JS rendering dominates crawl time & RAM; hard to parallelise

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#28]
**Component:** SeleniumManager coupling
**Category:** Performance
**Severity:** high

### Impact
JS rendering dominates crawl time & RAM; hard to parallelise

### Suggestion
Make JS rendering configurable per-domain; evaluate Playwright async pool

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: SeleniumManager coupling
category: Performance
severity: high
impact: JS rendering dominates crawl time & RAM; hard to parallelise
suggestion: Make JS rendering configurable per-domain; evaluate Playwright async pool
status: todo
```
