### ISSUE TITLE
[Async I/O & Concurrency tuning] Sequential blocking lowers throughput; won't meet daily re-crawl SLA

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#29]
**Component:** Async I/O & Concurrency tuning
**Category:** Performance
**Severity:** high

### Impact
Sequential blocking lowers throughput; won't meet daily re-crawl SLA

### Suggestion
Use asyncio-driven renderer workers; tune CONCURRENT_REQUESTS, auto-throttle

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Async I/O & Concurrency tuning
category: Performance
severity: high
impact: Sequential blocking lowers throughput; won't meet daily re-crawl SLA
suggestion: Use asyncio-driven renderer workers; tune CONCURRENT_REQUESTS, auto-throttle
status: todo
```
