### ISSUE TITLE
[Deduplication / Caching (URLs & Items)] Redundant fetches waste bandwidth; duplicates inflate dataset

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#30]
**Component:** Deduplication / Caching (URLs & Items)
**Category:** Performance
**Severity:** medium

### Impact
Redundant fetches waste bandwidth; duplicates inflate dataset

### Suggestion
Enable scrapy-deltafetch or hash-based URL cache + item fingerprinting

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Deduplication / Caching (URLs & Items)
category: Performance
severity: medium
impact: Redundant fetches waste bandwidth; duplicates inflate dataset
suggestion: Enable scrapy-deltafetch or hash-based URL cache + item fingerprinting
status: todo
```
