### ISSUE TITLE
[Memory Footprint on Large Pages] Big HTML (video portals) can OOM small containers

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#31]
**Component:** Memory Footprint on Large Pages
**Category:** Performance
**Severity:** low

### Impact
Big HTML (video portals) can OOM small containers

### Suggestion
Stream parse with lxml.iterparse or size guard before DOM-heavy ops

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Memory Footprint on Large Pages
category: Performance
severity: low
impact: Big HTML (video portals) can OOM small containers
suggestion: Stream parse with lxml.iterparse or size guard before DOM-heavy ops
status: todo
```
