### ISSUE TITLE
[FieldExtractor._match_field] Fuzzy mis-mapping leaks incorrect labels (director → cast, etc.)

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#32]
**Component:** FieldExtractor._match_field
**Category:** DataQuality
**Severity:** high

### Impact
Fuzzy mis-mapping leaks incorrect labels (director → cast, etc.)

### Suggestion
Threshold ≥ 80; log scores; switch fuzzywuzzy ➜ rapidfuzz for speed

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: FieldExtractor._match_field
category: DataQuality
severity: high
impact: Fuzzy mis-mapping leaks incorrect labels (director → cast, etc.)
suggestion: Threshold ≥ 80; log scores; switch fuzzywuzzy ➜ rapidfuzz for speed
status: todo
```
