### ISSUE TITLE
[CandidateExtractor recall/precision] Noisy blocks pass to Trafilatura, increasing false positives

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#33]
**Component:** CandidateExtractor recall/precision
**Category:** DataQuality
**Severity:** medium

### Impact
Noisy blocks pass to Trafilatura, increasing false positives

### Suggestion
Pre-filter blocks lacking ≥2 core fields (title/year/director)

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: CandidateExtractor recall/precision
category: DataQuality
severity: medium
impact: Noisy blocks pass to Trafilatura, increasing false positives
suggestion: Pre-filter blocks lacking ≥2 core fields (title/year/director)
status: todo
```
