### ISSUE TITLE
[Provenance Tracking] Hard to audit errors without source HTML/context

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#35]
**Component:** Provenance Tracking
**Category:** DataQuality
**Severity:** low

### Impact
Hard to audit errors without source HTML/context

### Suggestion
Store raw HTML hash + selector paths alongside parsed item

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Provenance Tracking
category: DataQuality
severity: low
impact: Hard to audit errors without source HTML/context
suggestion: Store raw HTML hash + selector paths alongside parsed item
status: todo
```
