### ISSUE TITLE
[Logging & Metrics] Limited visibility into crawl health, error spikes, rule misfires

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#36]
**Component:** Logging & Metrics
**Category:** Ops
**Severity:** high

### Impact
Limited visibility into crawl health, error spikes, rule misfires

### Suggestion
Structured JSON logs, Prometheus counters, Grafana dashboard

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Logging & Metrics
category: Ops
severity: high
impact: Limited visibility into crawl health, error spikes, rule misfires
suggestion: Structured JSON logs, Prometheus counters, Grafana dashboard
status: todo
```
