### ISSUE TITLE
[Retry / Backoff Strategy] Transient 5xx or 429 may lead to unnecessary failures

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#37]
**Component:** Retry / Backoff Strategy
**Category:** Ops
**Severity:** medium

### Impact
Transient 5xx or 429 may lead to unnecessary failures

### Suggestion
Exponential backoff + circuit-breaker on domain; alert on >N retries

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Retry / Backoff Strategy
category: Ops
severity: medium
impact: Transient 5xx or 429 may lead to unnecessary failures
suggestion: Exponential backoff + circuit-breaker on domain; alert on >N retries
status: todo
```
