### ISSUE TITLE
[Mock Mode Maintenance] Fixtures grow stale; tests diverge from prod reality

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#38]
**Component:** Mock Mode Maintenance
**Category:** Ops
**Severity:** low

### Impact
Fixtures grow stale; tests diverge from prod reality

### Suggestion
Provide "fixture refresh" script + CI job to flag diff vs live HTML

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Mock Mode Maintenance
category: Ops
severity: low
impact: Fixtures grow stale; tests diverge from prod reality
suggestion: Provide "fixture refresh" script + CI job to flag diff vs live HTML
status: todo
```
