### ISSUE TITLE
[Multilingual & Encoding Tests] UTF-8/Unicode edge cases break extraction on Burmese + mixed sites

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#39]
**Component:** Multilingual & Encoding Tests
**Category:** Testing
**Severity:** medium

### Impact
UTF-8/Unicode edge cases break extraction on Burmese + mixed sites

### Suggestion
Parametrised pytest fixtures with varied encodings; random sample fuzzing

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Multilingual & Encoding Tests
category: Testing
severity: medium
impact: UTF-8/Unicode edge cases break extraction on Burmese + mixed sites
suggestion: Parametrised pytest fixtures with varied encodings; random sample fuzzing
status: todo
```
