### ISSUE TITLE
[JavaScript-heavy Site Tests] Selenium logic untested in headless CI; regressions unnoticed

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#40]
**Component:** JavaScript-heavy Site Tests
**Category:** Testing
**Severity:** low

### Impact
Selenium logic untested in headless CI; regressions unnoticed

### Suggestion
GitHub Actions parallel job with xvfb / Playwright for JS examples

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: JavaScript-heavy Site Tests
category: Testing
severity: low
impact: Selenium logic untested in headless CI; regressions unnoticed
suggestion: GitHub Actions parallel job with xvfb / Playwright for JS examples
status: todo
```
