### ISSUE TITLE
[robots.txt / Policy Compliance] Legal or ethical violations against target sites

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#42]
**Component:** robots.txt / Policy Compliance
**Category:** Security
**Severity:** medium

### Impact
Legal or ethical violations against target sites

### Suggestion
Obey robots.txt + custom per-site exemptions list + user-agent string

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: robots.txt / Policy Compliance
category: Security
severity: medium
impact: Legal or ethical violations against target sites
suggestion: Obey robots.txt + custom per-site exemptions list + user-agent string
status: todo
```
