### ISSUE TITLE
[Request Rate-Limiting & IP Rotation] Gets blocked or captchas triggered

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#43]
**Component:** Request Rate-Limiting & IP Rotation
**Category:** Security
**Severity:** low

### Impact
Gets blocked or captchas triggered

### Suggestion
Polite delay per domain; rotating proxy pool w/ respect for TOS

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Request Rate-Limiting & IP Rotation
category: Security
severity: low
impact: Gets blocked or captchas triggered
suggestion: Polite delay per domain; rotating proxy pool w/ respect for TOS
status: todo
```
