### ISSUE TITLE
[Library Versions & CVE Scanning] Outdated Selenium / fuzzywuzzy pose security + performance risks

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#44]
**Component:** Library Versions & CVE Scanning
**Category:** Dependency
**Severity:** medium

### Impact
Outdated Selenium / fuzzywuzzy pose security + performance risks

### Suggestion
Pin in requirements-lock; dependabot + safety check in CI

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Library Versions & CVE Scanning
category: Dependency
severity: medium
impact: Outdated Selenium / fuzzywuzzy pose security + performance risks
suggestion: Pin in requirements-lock; dependabot + safety check in CI
status: todo
```
