### ISSUE TITLE
[Schema Versioning & Migrations] Breaking changes require backfills and API bumps

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#45]
**Component:** Schema Versioning & Migrations
**Category:** Storage
**Severity:** low

### Impact
Breaking changes require backfills and API bumps

### Suggestion
Adopt semantic version on MovieItem; migration scripts for DB

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Schema Versioning & Migrations
category: Storage
severity: low
impact: Breaking changes require backfills and API bumps
suggestion: Adopt semantic version on MovieItem; migration scripts for DB
status: todo
```
