### ISSUE TITLE
[Incremental Upserts] Full re-imports overwrite manual corrections

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#46]
**Component:** Incremental Upserts
**Category:** Storage
**Severity:** low

### Impact
Full re-imports overwrite manual corrections

### Suggestion
Upsert by (title, year) PK; keep "last_seen" + "changed" timestamps

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Incremental Upserts
category: Storage
severity: low
impact: Full re-imports overwrite manual corrections
suggestion: Upsert by (title, year) PK; keep "last_seen" + "changed" timestamps
status: todo
```
