### ISSUE TITLE
[Date / Number Localisation] Different calendars or Burmese numerals mis-parsed

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#47]
**Component:** Date / Number Localisation
**Category:** i18n
**Severity:** low

### Impact
Different calendars or Burmese numerals mis-parsed

### Suggestion
Use dateparser with "languages=['my', 'en']"; normalise numerals

---
*This issue is managed by the issue sync tool. Please do not modify this section.*
```yaml
component: Date / Number Localisation
category: i18n
severity: low
impact: Different calendars or Burmese numerals mis-parsed
suggestion: Use dateparser with "languages=['my', 'en']"; normalise numerals
status: todo
```
