### ISSUE TITLE
[MissingComponent] test

### ISSUE THREAD

**Issue by kaungkhantko** [kaungkhantko/BRAWL-Burmese-movies-cRAWLer-#98]
```yaml
category: DataQuality
component: MissingComponent
impact: test
severity: medium
status: todo
suggestion: x
```
